<?php

if  ($_GET['id'] == 'allasset')
{
session_start(); 
$usename = $_SESSION['dashboard_user'];
date_default_timezone_set('Asia/Kuala_Lumpur');
$time = date('d-m-Y H:i:s');
shell_exec("cp -f dumpallasset.csv AllActiveITAssets.csv");

shell_exec("echo \"Report generated by:;".$usename.";On;".$time."\" >> AllActiveITAssets.csv");

header ('Location: AllActiveITAssets.csv');

}
else if  ($_GET['id'] == 'nda')
{
session_start(); 
$usename = $_SESSION['dashboard_user'];
date_default_timezone_set('Asia/Kuala_Lumpur');
$time = date('d-m-Y H:i:s');
shell_exec("cp -f dumpnda.csv NewlyDiscoverITAsset.csv");

shell_exec("echo \"Report generated by:;".$usename.";On;".$time."\" >> NewlyDiscoverITAsset.csv");

header ('Location: NewlyDiscoverITAsset.csv');

}


?>