<?php
include('login/db_configs.php');
session_start(); 
$usename = $_SESSION['dashboard_user'];
date_default_timezone_set('Asia/Kuala_Lumpur');
$time = date('d-m-Y H:i:s');
if  ($_GET['gen'] == 'SAA')
{
    
$sql = "SELECT *
FROM `glpi_active_chart`
order by dateime desc limit 1";
$result = $conn->query($sql);
  
if ($result->num_rows > 0) {
//
    $xxx1 = "Report generated by: ;".$usename."; On ;".$time;
   $xxx4 = "  ;  " ;

   $xxx2 = "IT Asset Type ; Total" ;
    // output data of each row
    while($row = $result->fetch_assoc()) {
         $xxx3 = "Desktop ;".$row['desktop'];
         $xxx5 = "Laptop ;".$row['laptop'];
         $xxx6 = "Server ;".$row['server'];
         $xxx7 = "Printer ;".$row['printer'];
         $xxx8 = "Network ;".$row['network'];
         $xxx9 = "Storage;".$row['storage'];
     $desktop = $row["desktop"];
     $laptop = $row["laptop"];
     $server = $row["server"];
     $printer = $row["printer"];
     $network = $row["network"];
     $storage = $row["storage"];
     $time = $row["dateime"];
//        echo $desktop;
//        echo $time;
    }
} else {
       $desktop = '0';
     $laptop = '0';
     $server = '0';
     $printer = '0';
     $network = '0';
     $storage = '0';
         $xxx3 = "Desktop ;0";
         $xxx5 = "Laptop ;0";
         $xxx6 = "Server ;0";
         $xxx7 = "Printer ;0";
         $xxx8 = "Network ;0";
         $xxx9 = "Storage ;0";
}
 $filename = "AllActiveITAsset.csv";

 
  header('Content-Type: text/csv; charset=utf-8');

  header('Content-Disposition: attachment; filename='.$filename);
  $output = fopen("php://output","w");
    
//  fputcsv($output, array('Report generated by:';$usename;'On';$time));  

//  fputcsv($output, array('IT Asset Type';'Total'));  
//fputcsv($output,  array('Desktop';$desktop));  
//fputcsv($output,  array('Laptop';$laptop));  
//fputcsv($output,  array('Server';$server));  
//fputcsv($output,  array('Printer';$printer));  
//fputcsv($output,  array('Network';$network));  
//fputcsv($output,  array('Storage';$storage));  
//fputcsv($output,  $xxx);  

  fputcsv($output,explode(';',$xxx1), ";" );
      fputcsv($output,explode(';',$xxx4), ";" );

  fputcsv($output,explode(';',$xxx2), ";" );
  fputcsv($output,explode(';',$xxx3), ";" );
  fputcsv($output,explode(';',$xxx5), ";" );
  fputcsv($output,explode(';',$xxx6), ";" );
  fputcsv($output,explode(';',$xxx7), ";" );
  fputcsv($output,explode(';',$xxx8), ";" );
  fputcsv($output,explode(';',$xxx9), ";" );
  
fclose($output);
$conn->close();
}

else if ($_GET['gen'] == 'SDeA')
{
  $month =  date("F");      
$sql = "SELECT *
FROM `glpi_decom_chart_month`
order by dateime desc limit 1";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
//
    $xxx1 = "Report generated by: ;".$usename."; On ;".$time;
   $xxx4 = "  ;  " ;

   $xxx2 = "IT Asset Type ; Total" ;
    // output data of each row
    while($row = $result->fetch_assoc()) {
         $xxx3 = "Desktop ;".$row['desktop'];
         $xxx5 = "Laptop ;".$row['laptop'];
         $xxx6 = "Server ;".$row['server'];
         $xxx7 = "Printer ;".$row['printer'];
         $xxx8 = "Network ;".$row['network'];
         $xxx9 = "Storage;".$row['storage'];
     $desktop = $row["desktop"];
     $laptop = $row["laptop"];
     $server = $row["server"];
     $printer = $row["printer"];
     $network = $row["network"];
     $storage = $row["storage"];
     $time = $row["dateime"];
//        echo $desktop;
//        echo $time;
    }
} else {
       $desktop = '0';
     $laptop = '0';
     $server = '0';
     $printer = '0';
     $network = '0';
     $storage = '0';
         $xxx3 = "Desktop ;0";
         $xxx5 = "Laptop ;0";
         $xxx6 = "Server ;0";
         $xxx7 = "Printer ;0";
         $xxx8 = "Network ;0";
         $xxx9 = "Storage ;0";
}
 $filename = "DecomITAsset_".$month.".csv";

 
  header('Content-Type: text/csv; charset=utf-8');

  header('Content-Disposition: attachment; filename='.$filename);
  $output = fopen("php://output","w");
  fputcsv($output,explode(';',$xxx1), ";" );
      fputcsv($output,explode(';',$xxx4), ";" );

  fputcsv($output,explode(';',$xxx2), ";" );
  fputcsv($output,explode(';',$xxx3), ";" );
  fputcsv($output,explode(';',$xxx5), ";" );
  fputcsv($output,explode(';',$xxx6), ";" );
  fputcsv($output,explode(';',$xxx7), ";" );
  fputcsv($output,explode(';',$xxx8), ";" );
  fputcsv($output,explode(';',$xxx9), ";" );
  
fclose($output);
$conn->close();

}
else if ($_GET['gen'] == 'SDiA')
{
  $month =  date("F");      
$sql = "SELECT *
FROM `glpi_dist_chart_month`
order by dateime desc limit 1";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
//
    $xxx1 = "Report generated by: ;".$usename."; On ;".$time;
   $xxx4 = "  ;  " ;

   $xxx2 = "IT Asset Type ; Total" ;
    // output data of each row
    while($row = $result->fetch_assoc()) {
         $xxx3 = "Desktop ;".$row['desktop'];
         $xxx5 = "Laptop ;".$row['laptop'];
         $xxx6 = "Server ;".$row['server'];
         $xxx7 = "Printer ;".$row['printer'];
         $xxx8 = "Network ;".$row['network'];
         $xxx9 = "Storage;".$row['storage'];
     $desktop = $row["desktop"];
     $laptop = $row["laptop"];
     $server = $row["server"];
     $printer = $row["printer"];
     $network = $row["network"];
     $storage = $row["storage"];
     $time = $row["dateime"];
//        echo $desktop;
//        echo $time;
    }
} else {
       $desktop = '0';
     $laptop = '0';
     $server = '0';
     $printer = '0';
     $network = '0';
     $storage = '0';
         $xxx3 = "Desktop ;0";
         $xxx5 = "Laptop ;0";
         $xxx6 = "Server ;0";
         $xxx7 = "Printer ;0";
         $xxx8 = "Network ;0";
         $xxx9 = "Storage ;0";
}
 $filename = "DisposedITAsset_".$month.".csv";

 
  header('Content-Type: text/csv; charset=utf-8');

  header('Content-Disposition: attachment; filename='.$filename);
  $output = fopen("php://output","w");
  fputcsv($output,explode(';',$xxx1), ";" );
      fputcsv($output,explode(';',$xxx4), ";" );

  fputcsv($output,explode(';',$xxx2), ";" );
  fputcsv($output,explode(';',$xxx3), ";" );
  fputcsv($output,explode(';',$xxx5), ";" );
  fputcsv($output,explode(';',$xxx6), ";" );
  fputcsv($output,explode(';',$xxx7), ";" );
  fputcsv($output,explode(';',$xxx8), ";" );
  fputcsv($output,explode(';',$xxx9), ";" );
  
fclose($output);
$conn->close();

}
else if ($_GET['gen'] == 'PG')
{
  $month =  date("F");      
$sql = "SELECT *
FROM `glpi_PG`
order by dateime desc limit 1";
$result = $conn->query($sql);
$xxx1 = "Report generated by: ;".$usename."; On ;".$time;
   $xxx4 = "  ;  " ;

   $xxx2 = "IT Asset Type ; Total" ;
if ($result->num_rows > 0) {
//
    
    // output data of each row
    while($row = $result->fetch_assoc()) {
         $xxx3 = "Desktop ;".$row['desktop'];
         $xxx5 = "Laptop ;".$row['laptop'];
         $xxx6 = "Server ;".$row['server'];
         $xxx7 = "Printer ;".$row['printer'];
         $xxx8 = "Network ;".$row['network'];
         $xxx9 = "Storage;".$row['storage'];
     $desktop = $row["desktop"];
     $laptop = $row["laptop"];
     $server = $row["server"];
     $printer = $row["printer"];
     $network = $row["network"];
     $storage = $row["storage"];
     $time = $row["dateime"];
//        echo $desktop;
//        echo $time;
    }
} else {
       $desktop = '0';
     $laptop = '0';
     $server = '0';
     $printer = '0';
     $network = '0';
     $storage = '0';
         $xxx3 = "Desktop ;0.00";
         $xxx5 = "Laptop ;0.00";
         $xxx6 = "Server ;0.00";
         $xxx7 = "Printer ;0.00";
         $xxx8 = "Network ;0.00";
         $xxx9 = "Storage ;0.00";
}
 $filename = "Profit_Gained.csv";

 
  header('Content-Type: text/csv; charset=utf-8');

  header('Content-Disposition: attachment; filename='.$filename);
  $output = fopen("php://output","w");
  fputcsv($output,explode(';',$xxx1), ";" );
      fputcsv($output,explode(';',$xxx4), ";" );

  fputcsv($output,explode(';',$xxx2), ";" );
  fputcsv($output,explode(';',$xxx3), ";" );
  fputcsv($output,explode(';',$xxx5), ";" );
  fputcsv($output,explode(';',$xxx6), ";" );
  fputcsv($output,explode(';',$xxx7), ";" );
  fputcsv($output,explode(';',$xxx8), ";" );
  fputcsv($output,explode(';',$xxx9), ";" );
  
fclose($output);
$conn->close();

}


?>